### ISSUE TITLE
Napalm artillery tower doesn't seem to power up even with magma clearly attached

### ISSUE THREAD

**Issue by Ambient-Impact** [TheKilltech/rift_balance#5]
I've only tested this on the acid biome, since I couldn't even get the tower to place on the ground in the swamp biome where it would have come in very handy. That's a bug for another time though.

![Image](https://github.com/user-attachments/assets/30e9186d-3b02-4663-a84a-4f34515fcd63)

What's weird is that the pipeline clearly shows both towers consuming 50 magma a second:

![Image](https://github.com/user-attachments/assets/b9ae0897-00ee-4997-b422-352b4a421319)

**Comment by TheKilltech** [comment]
good catch. i think i found both issues and hopefully fixed them. pushed it to the dev branch (but had no time to test it myself). maybe you can test that and close the issue if its fixed?

- one issue was that originally artillery towers were white-listed for biomes (not allowed in caverns). DLC3 changed that to a black list so no update is needed whenever a new biome is added. the new variants i made were not updated when i merged with the official DLC changes.
- the issue with the liquid requirement is simpler. magma input was in the wrong resource group, so the game interpreted this tower to require two different liquids but has only an input for one, so its unusable. i fixed that. now it should need only one fuel while accepting a wider range of fluids.

**Comment by Ambient-Impact** [comment]
Alas, even after pulling in your changes, it's still showing them the same as in the screenshot above. 😭

**Comment by TheKilltech** [comment]
Hmm, did you rebuild the towers? any change made to the mod files only affects blueprints i.e. only newly build structures. The ones from older save will keep their stats - including the buggy behavior. i think this is why the devs added a cheat to rebuild all buildings on the map.

this behavior is a bit unintuitive but that's how the game works. tricked me a few times.

**Comment by Ambient-Impact** [comment]
I did try to build a new one but I used the picker tool on the old towers so maybe that's causing the game to try to build using the previous version? I can try to select it manually when I'm home tonight and see if that works.

That behaviour may be a bit unintuitive to the player but it makes perfect sense for such a moddable game to minimize breaking save files, which I assume is why it works that way.

**Comment by Ambient-Impact** [comment]
Correct you were! Holy crap, they work when I didn't use the picker tool on the old ones. Thanks!

**Comment by TheKilltech** [comment]
Ah, perfect, thanks!
the behavior of the picker tool is interesting though.
